# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  all-dependencies:
    target-branch: "develop"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/Berlin"
    assignees:
      - "JohannesKnecht"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 1
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "npm"
    directory: "/frontend/AnkiAICardCreationFrontend"
    cooldown:
      default-days: 1
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "uv"
    directory: "/backend/AnkiAICardCreationToolboxBackend"
    cooldown:
      default-days: 1
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "docker"
    directories:
      - "/backend/AnkiAICardCreationToolboxBackend"
      - "/frontend/AnkiAICardCreationFrontend"
    cooldown:
      default-days: 1
    multi-ecosystem-group: "all-dependencies"
